name: Unit Tests & Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-latest

    permissions:
      pull-requests: write
      contents: read
    timeout-minutes: 30

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠️ Show Xcode Version
        working-directory: community_swift
        run: xcodebuild -version

      - name: 💎 Install Ruby Gems (xcov)
        working-directory: community_swift
        run: sudo gem install xcov

      - name: 🏃 Run Unit Tests
        working-directory: community_swift
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme community_swift \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -enableCodeCoverage YES \
            -derivedDataPath ./DerivedData \
            | xcpretty

      - name: 📝 Generate Coverage Report
        id: coverage
        working-directory: community_swift
        run: |
          xcov \
            -p community_swift.xcodeproj \
            --derived_data_path ./DerivedData \
            --scheme community_swift \
            --output_directory ./xcov_output \
            --exclude_targets "community_swift.app" \
            --minimum_coverage 80 \
            --markdown_report

      - name: 📦 Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverageReport
          path: community_swift/xcov_output
          retention-days: 7

      - name: 💬 Post Coverage Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: community_swift/community_swift/xcov_output/report.md
